"""add streak and class fields

Revision ID: f6b83b11c519
Revises: 0736c7ff6722
Create Date: 2026-08-02 11:15:00.489434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b83b11c519'
down_revision: Union[str, Sequence[str], None] = '0736c7ff6722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_tree', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('skill_tree', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_skill_tree_parent'), table_name='skill_tree')
    op.drop_constraint(op.f('skill_tree_parent_id_fkey'), 'skill_tree', type_='foreignkey')
    op.create_foreign_key(None, 'skill_tree', 'skill_tree', ['parent_id'], ['skill_id'])
    op.alter_column('study_sessions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('study_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('user_progression', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_progression', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_progression', sa.Column('last_study_date', sa.Date(), nullable=True))
    op.add_column('user_progression', sa.Column('learner_class', sa.String(), nullable=True))
    op.alter_column('user_progression', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_skill_unlocks', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_skill_unlocks', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_progression', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_progression', 'learner_class')
    op.drop_column('user_progression', 'last_study_date')
    op.drop_column('user_progression', 'longest_streak')
    op.drop_column('user_progression', 'current_streak')
    op.alter_column('study_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_sessions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'skill_tree', type_='foreignkey')
    op.create_foreign_key(op.f('skill_tree_parent_id_fkey'), 'skill_tree', 'skill_tree', ['parent_id'], ['skill_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_skill_tree_parent'), 'skill_tree', ['parent_id'], unique=False)
    op.alter_column('skill_tree', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('skill_tree', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
